export const FETCH_EQUIPMENT_USAGE_REQUEST = 'FETCH_EQUIPMENT_USAGE_REQUEST';
export const FETCH_EQUIPMENT_USAGE_SUCCESS = 'FETCH_EQUIPMENT_USAGE_SUCCESS';
export const FETCH_EQUIPMENT_USAGE_FAILURE = 'FETCH_EQUIPMENT_USAGE_FAILURE';
