export const FETCH_TRAINERS_REQUEST = 'FETCH_TRAINERS_REQUEST';
export const FETCH_TRAINERS_SUCCESS = 'FETCH_TRAINERS_SUCCESS';
export const FETCH_TRAINERS_FAILURE = 'FETCH_TRAINERS_FAILURE';
export const SET_AVAILABLE_TRAINER_IDS = 'SET_AVAILABLE_TRAINER_IDS';
