export const FETCH_TRAINER_TIMESLOTS_REQUEST = 'FETCH_TRAINER_TIMESLOTS_REQUEST';
export const FETCH_TRAINER_TIMESLOTS_SUCCESS = 'FETCH_TRAINER_TIMESLOTS_SUCCESS';
export const FETCH_TRAINER_TIMESLOTS_FAILURE = 'FETCH_TRAINER_TIMESLOTS_FAILURE';
